name: Build SunamoCsproj

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoCsproj
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCsproj/SunamoCsproj.csproj

    - name: Build
      run: dotnet build SunamoCsproj/SunamoCsproj.csproj --configuration Release --no-restore

  test:
    name: Test SunamoCsproj.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCsproj.Tests/SunamoCsproj.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoCsproj.Tests/SunamoCsproj.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoCsproj.Tests/SunamoCsproj.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
